# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d736537d241cd7c2b077f254aca843bfb3b203756c1ef4830f36c709b0dfc3b0834f621b4db536723ad29aa20592d4dea2250fdcda2dcd1362de38658acd9bc

test:
  secret_key_base: f66964f2c7e0361ed99c0ba4a4d19b4931060d550fc0f02653532740e481d2b02c14a8b49b9b70dc0079ac5caced0873c0d66ec74ce8aa201122ff5331c2c15b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
